### PR TITLE
Added PatternFly Vertical Navigation

### PR DESCRIPTION
**Pull request by SachinRammoorthy**
GCI Task: https://codein.withgoogle.com/dashboard/task-instances/5642576046587904/

Here is a screenshot of the changes:

________
screen shot 2017-12-14 at 5 16 48 pm

screen shot 2017-12-14 at 10 57 01 am

### CODE REVIEW

**Comment by garg-anuj** [comment]
@SachinRammoorthy You did good but link we provided and wanted was vertical nav and no etra content on page. Here you have created horizontal navigation.

You will need to switch to vertical nav and remove extra content. Otherwise great work 🎉

**Comment by garg-anuj** [comment]
Also you installed with `npm install patternfly`. You will also need to do `npm install --save patternfly` so that dep get stored in package.json

**Comment by SachinRammoorthy** [comment]
Hey @garg-anuj . Removed the content of the page, but its more complicated to switch to vertical navigation. i am trying now. Also installed patternfly properly.

**Comment by SachinRammoorthy** [comment]
Hey @garg-anuj added vertical navigation. pls see

**Comment by SachinRammoorthy** [comment]
Complete with dependencies, empty content, and vertical navigation.

**Comment by garg-anuj** [comment]
Awesome work @SachinRammoorthy 👍 🎉

**Pull request closed without merging**
